# Taint Node: kubectl taint nodes node1 app=blue:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod

spec:
  containers:
  - name: nginx-container
    image: nginx
  tolerations:
  # remember these values need to be encoded with double quotes(")
  - key: "app"
    operator: "equal"
    value: "blue"
    effect: "NoSchedule"