apiVersion: v1
kind: Pod
metadata:
  name: my-app
  label:
    name: my-app
spec:
  containers:
  - name: my-app
    image: my-app
    containerPort: 8080

  resources:
    requests:
      memory: "1Gi"
      cpu: 1