apiVersion: v1
kind: Pod
metadata:
  name: my-app
  label:
    name: my-app
spec:
  containers:
  - name: my-app
    image: my-app
    ports:
    - containerPort: 8080

    resources:
      requests:
        memory: "1Gi"
        cpu: 1

    limits:
      memory: "2Gi"
      cpu: 2