apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp

  # label and selector goes here!
  labels:
    app: app1
    function: back-end
  # labelEnd

spec:
  containers:
  -  name: simple-webapp
     image: simeple-webapp
     ports:
       - containerPort: 8080

# kubectl get pods --selector app=app1